### ISSUE TITLE
Update ProductId Page

### ISSUE THREAD

**Issue by jiaweiteo** [lyeyixian/acfirst-web#7]
- [x] 1. Add related products carousel at the bottom of the page
- [x] - Get related by 4 fields, followed by 3 fields, then 2 fields. Afterwhich show 10 products
- [x] 2. Change title to breadcrumbs
- [x] - Products —> Categories —> Code
- [x] 3. Zoom in on image (Low priority)
- [x] 4. Remove description
- [x] 5. Add related item code in product page with small image
- [x] 6. Remove code in specification
- [x] 7. Add quantity

**Comment by lyeyixian** [comment]
https://codesandbox.io/s/image-zoom-on-hover-i50bq?file=/src/App.js:0-2160

for zoom thingy
